# Generated by Django 5.1.1 on 2024-10-01 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suppli_request', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suppliresquest',
            name='created_by',
        ),
        migrations.DeleteModel(
            name='ItensSupplyRequest',
        ),
        migrations.DeleteModel(
            name='SuppliResquest',
        ),
    ]
