# Generated by Django 5.1.1 on 2024-10-02 04:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppli_request', '0003_initial'),
        ('supplier', '0008_delete_requestsupplier'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modificado em')),
                ('price_proposal', models.FloatField(verbose_name='Preço da cotação')),
                ('validity', models.DateField(verbose_name='Validade')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
                ('item_request', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='suppli_request.itenssupplyrequest', verbose_name='Item da Requisição')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='suppli_request.supplyresquest', verbose_name='Requisição de Fornecimento')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='supplier.supplier', verbose_name='Fornecedor')),
            ],
            options={
                'verbose_name': 'Proposal',
                'verbose_name_plural': 'Proposals',
            },
        ),
    ]
