# Generated by Django 5.1.1 on 2024-10-05 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppli_request', '0004_proposal'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proposal',
            options={'verbose_name': 'Cotação', 'verbose_name_plural': 'Cotações'},
        ),
        migrations.AddField(
            model_name='proposal',
            name='is_aproved',
            field=models.BooleanField(default=False, verbose_name='Aprovada'),
        ),
    ]
