# Generated by Django 5.1.1 on 2024-10-05 22:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppli_request', '0005_alter_proposal_options_proposal_is_aproved'),
        ('supplier', '0009_alter_phonecontact_contact_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplyresquest',
            name='delivery_time',
            field=models.DateField(blank=True, null=True, verbose_name='Prazo de Entrega'),
        ),
        migrations.AddField(
            model_name='supplyresquest',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Inicio do Contrato'),
        ),
        migrations.AddField(
            model_name='supplyresquest',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='supplier.supplier', verbose_name='Fornecedor'),
        ),
        migrations.DeleteModel(
            name='Proposal',
        ),
    ]
