# Generated by Django 5.1.1 on 2024-10-19 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppli_request', '0006_supplyresquest_delivery_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itenssupplyrequest',
            name='total_value',
            field=models.FloatField(blank=True, null=True, verbose_name='Valor Total'),
        ),
    ]
