# Generated by Django 5.1.1 on 2024-10-19 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suppli_request', '0007_itenssupplyrequest_total_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itenssupplyrequest',
            name='total_value',
        ),
    ]
