# Generated by Django 5.1.1 on 2024-09-20 23:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactSupplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, verbose_name='Nome')),
                ('last_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Sobrenome')),
                ('position_company', models.CharField(max_length=50, verbose_name='Cargo na Empresa')),
                ('e_mail', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('remarks', models.CharField(blank=True, max_length=254, null=True, verbose_name='Observações')),
            ],
            options={
                'verbose_name': 'Contato do Fornecedor',
                'verbose_name_plural': 'Contatos dos Fornecedores',
            },
        ),
        migrations.CreateModel(
            name='ResquestSupplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_date', models.DateField(verbose_name='Data da Requisição')),
                ('reson_hiring', models.CharField(max_length=254, verbose_name='Motivo da Contratação')),
                ('contract_value', models.FloatField(verbose_name='Valor Total do Contrato')),
                ('status', models.CharField(choices=[('IT', 'Iniciado'), ('PL', 'Paralizado'), ('IP', 'Em andamento'), ('FN', 'Finalizado'), ('CP', 'Concluido')], default='IT', max_length=2, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Requisição ao Fornecedor',
                'verbose_name_plural': 'Requisições aos Fornecedores',
            },
        ),
        migrations.CreateModel(
            name='PhoneContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_phone', models.CharField(choices=[('LL', 'Telefone Fixo'), ('MB', 'Celular')], default='MB', max_length=2, verbose_name='Telefone')),
                ('ddi_number', models.CharField(blank=True, max_length=3, null=True, verbose_name='DDI')),
                ('ddd_number', models.CharField(max_length=2, verbose_name='DDD')),
                ('phone_number', models.CharField(max_length=9, verbose_name='Número')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supplier.contactsupplier', verbose_name='Telefone')),
            ],
            options={
                'verbose_name': 'Telefones do Contato',
                'verbose_name_plural': 'Telefones dos Contatos',
            },
        ),
        migrations.CreateModel(
            name='PhoneSupplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_phone', models.CharField(choices=[('LL', 'Telefone Fixo'), ('MB', 'Celular')], default='MB', max_length=2, verbose_name='Telefone')),
                ('ddi_number', models.CharField(blank=True, max_length=3, null=True, verbose_name='DDI')),
                ('ddd_number', models.CharField(max_length=2, verbose_name='DDD')),
                ('phone_number', models.CharField(max_length=9, verbose_name='Número')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supplier.contactsupplier', verbose_name='Telefone')),
            ],
            options={
                'verbose_name': 'Telefones do Contato',
                'verbose_name_plural': 'Telefones dos Contatos',
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modificado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('company_name', models.CharField(max_length=150, verbose_name='Razão Social')),
                ('fantasy_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Nome Fantasia')),
                ('cnpj_number', models.CharField(blank=True, max_length=14, verbose_name='CNPJ')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Fornecedor',
                'verbose_name_plural': 'Fornecedores',
            },
        ),
        migrations.AddField(
            model_name='contactsupplier',
            name='supplier_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supplier.supplier', verbose_name='Fornecedores'),
        ),
    ]
