# Generated by Django 5.1.1 on 2024-09-20 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ResquestSupplier',
            new_name='RequestSupplier',
        ),
    ]
