# Generated by Django 5.1.1 on 2024-09-21 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0002_rename_resquestsupplier_requestsupplier'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RequestSupplier',
        ),
    ]
