# Generated by Django 5.1.1 on 2024-09-21 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0004_requestsupplier'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PhoneSupplier',
        ),
    ]
