# Generated by Django 5.1.1 on 2024-09-21 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0005_delete_phonesupplier'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneSupplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_phone', models.CharField(choices=[('LL', 'Telefone Fixo'), ('MB', 'Celular')], default='MB', max_length=2, verbose_name='Telefone')),
                ('ddi_number', models.CharField(blank=True, max_length=3, null=True, verbose_name='DDI')),
                ('ddd_number', models.CharField(max_length=2, verbose_name='DDD')),
                ('phone_number', models.CharField(max_length=9, verbose_name='Número')),
                ('supplier_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supplier.supplier', verbose_name='Telefone')),
            ],
            options={
                'verbose_name': 'Telefones do Contato',
                'verbose_name_plural': 'Telefones dos Contatos',
            },
        ),
    ]
