# Generated by Django 5.1.1 on 2024-09-21 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0006_phonesupplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='e_mail',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail'),
        ),
    ]
