# Generated by Django 5.1.1 on 2024-10-02 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0007_supplier_e_mail'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RequestSupplier',
        ),
    ]
