# Generated by Django 5.1.1 on 2024-10-05 22:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0008_delete_requestsupplier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonecontact',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supplier.contactsupplier', verbose_name='Contato'),
        ),
        migrations.AlterField(
            model_name='phonesupplier',
            name='supplier_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supplier.supplier', verbose_name='Fornecedor'),
        ),
    ]
